
name: SWA Preview Teardown

on:
  pull_request:
    types: [closed]

jobs:
  close_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Remove SWA Preview Environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
          azure_static_web_apps_api_token: ${{ secrets.SWA_TOKEN }}
